#This image contains the RHCOS livecd.iso
FROM quay.io/ocpmetal/livecd-iso:rhcos-livecd AS livecd-build
RUN chmod 666 /root/image/livecd.iso

FROM python:3-slim
ARG WORK_DIR=/data

RUN mkdir $WORK_DIR
RUN chmod 777 $WORK_DIR

COPY --from=livecd-build /root/image/livecd.iso $WORK_DIR
ENV COREOS_IMAGE=$WORK_DIR/livecd.iso

COPY requirements.txt /tmp/requirements.txt
RUN pip install -r /tmp/requirements.txt

RUN rm /tmp/*requirements.txt

COPY ./coreos-installer $WORK_DIR
COPY ./install_process.py $WORK_DIR

ENV WORK_DIR=$WORK_DIR

CMD python /data/install_process.py
